SELECT 
    KCU1.TABLE_NAME AS 'Child_Table', 
    KCU1.COLUMN_NAME AS 'Child_Column', 
    KCU2.TABLE_NAME AS 'Parent_Table', 
    KCU2.COLUMN_NAME AS 'Parent_Column',
    RC.CONSTRAINT_NAME AS 'Relationship_Name'
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS RC
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU1 
    ON RC.CONSTRAINT_NAME = KCU1.CONSTRAINT_NAME
INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU2 
    ON RC.UNIQUE_CONSTRAINT_NAME = KCU2.CONSTRAINT_NAME
    AND KCU1.ORDINAL_POSITION = KCU2.ORDINAL_POSITION
ORDER BY Child_Table;